name: Ponto_Riobranco
description: App de ponto eletronico feito em flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # new path
  path_provider: ^2.0.1
  # acesso a galeria
  image_picker: ^0.8.4+4
  #form data/request
  dio: ^4.0.0
  #send file
  http_parser: ^4.0.0
  #axios data send
  axios: ^1.0.1+1
  #geolocator referenciamento de localização
  geolocator: ^7.0.3
  #modal_progress_hud
  modal_progress_hud: ^0.1.3
  #biblioteca do splash
  flutter_spinkit: ^5.1.0
  #laucher ico do app
  flutter_launcher_icons: ^0.9.0
  # Data may be persisted to disk asynchronously
  shared_preferences: ^2.0.6
  #Ele define a classe Intl, com a localidade padrão e métodos para acessar a maioria dos mecanismos de internacionalização.
  intl: ^0.17.0
  #Bivliotec de Icones variadas
  flutter_svg: ^0.23.0+1
  #Gerador de configuração específico do ambiente.
  #Permite especificar a configuração de env durante a construção de CI / CD.
  #Criado principalmente para simplificar a configuração de construção do Flutter.
  environment_config: ^3.0.0

  flutter_modular: ^4.2.0
  # Um invólucro em torno de InheritedWidget para torná-los mais fáceis de usar e mais reutilizáveis.
  provider: ^6.0.1
  # Plugin Flutter para descobrir o estado da conectividade da rede (Wi-Fi e móvel / celular) no Android e iOS.
  connectivity: ^3.0.6
  # suporte de fornecedor para sobreposição, fácil de construir brinde e notificação interna
  overlay_support: ^1.2.1
  # pdf view (viazualização de pdf no App)
  flutter_pdfview: ^1.1.0
  # Este plugin fornece uma API de plataforma cruzada (iOS, Android) para solicitar permissões e verificar seu status.
  permission_handler: ^8.1.6
  # Isso significa referir-se à autenticação biométrica no iOS (Touch ID ou código de bloqueio) e às APIs de impressão digital no Android (introduzidas no Android 6.0).
  local_auth: ^1.1.7
  # popup de menu criado em dart para ios e android
  popup_menu: ^1.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter




flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo-amac.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
#      - family: Nunito
#        fonts:
#          - asset: assets/fonts/Nunito-Regular.ttf
#          - asset: assets/fonts/Nunito-Bold.ttf
#            weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
